version: '3.8'

services:
  gestion-classes:
    container_name: gestion-classes
    build: ./gestion-classes
    ports:
      - "8001:80"
    networks:
      - app-network
    restart: unless-stopped

  gestion-cours:
    container_name: gestion-cours
    build: ./gestion-cours
    ports:
      - "8002:80"
    networks:
      - app-network
    restart: unless-stopped

  gestion-professeurs:
    container_name: gestion-professeurs
    build: ./gestion-professeurs
    ports:
      - "8003:80"
    networks:
      - app-network
    restart: unless-stopped

  gestion-etudiants:
    container_name: gestion-etudiants
    build: ./gestion-etudiants
    ports:
      - "8004:80"
    networks:
      - app-network
    restart: unless-stopped

  gestion-emploi:
    container_name: gestion-emploi
    build: ./gestion-emploi
    ports:
      - "8005:80"
    networks:
      - app-network
    restart: unless-stopped

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"  
      - "50000:50000"  
    volumes:
      - jenkins_home:/var/jenkins_home  
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  
    restart: unless-stopped

  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest  
    volumes:
      - .:/workspace  
    working_dir: /workspace  
    networks:
      - app-network
    environment:
      - TF_VAR_project_name=projet-devops  
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
