sonar.projectKey=Mareme-kane_projet-devops
sonar.organization=mareme-kane

sonar.sources=app,resources
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**

sonar.host.url=https://sonarcloud.io
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.phpunit.reportPath=test-reports/phpunit.xml
sonar.phpunit.coverageReportPath=coverage.xml
